### ISSUE TITLE
Let's use yarn instead of NPM here's why. 

### ISSUE THREAD

**Issue by RustyRaptor** [konishi-project/zimmerman#69]
I noticed we are managing dependencies with NPM (I think) 
We should switch to yarn. https://yarnpkg.com/en/ 
It's much faster and more secure and is the industry standard. I'll test to see if we can just use it right off the bat. It usually just involves running yarn install on the repo and nothing else.

**Comment by RustyRaptor** [comment]
UPDATE: looks like yarn works out of the box. We just have to replace the lock file.

**Comment by RustyRaptor** [comment]
And of course, put instructions to use yarn in the README :)

**Comment by X1Zeth2X** [comment]
I think this should be discussed in the frontend section (Kagawasan).
https://github.com/X1Zeth2X/kagawasan - I will move this repository to the
main konishi-project once I clean up most of the code and fixed issues/bugs.

**Comment by RustyRaptor** [comment]
Didn't even realize we moved it to a different repo my bad.
